// filename: DataLoader.java
// Code Generated by Sidekick is for learning and experimentation purposes only.

package SpringAI.FinanceRAG;

import jakarta.annotation.PostConstruct;
import java.io.InputStream;
import java.util.ArrayList;
import java.util.List;
import org.apache.tika.Tika;
import org.springframework.ai.document.Document;
import org.springframework.ai.vectorstore.VectorStore;
import org.springframework.beans.factory.annotation.Value;
import org.springframework.core.io.Resource;
import org.springframework.jdbc.core.simple.JdbcClient;
import org.springframework.stereotype.Component;

@Component
public class DataLoader {

    private static final int CHUNK_SIZE = 1000;
    private static final int CHUNK_OVERLAP = 200;

    private final VectorStore vectorStore;
    private final JdbcClient jdbcClient;

    @Value("classpath:/article_thebeatoct2024.pdf")
    private Resource pdfResource;

    public DataLoader(VectorStore vectorStore, JdbcClient jdbcClient) {
        this.vectorStore = vectorStore;
        this.jdbcClient = jdbcClient;
    }

    @PostConstruct
    public void init() {
        Integer count = jdbcClient.sql("select count(*) from vector_store")
                .query(Integer.class)
                .single();

        System.out.println("No of records in the PG vector store: " + count);

        if (count != null && count > 0) {
            return;
        }

        try (InputStream inputStream = pdfResource.getInputStream()) {
            System.out.println("Loading the article using Tika");

            Tika tika = new Tika();
            String text = tika.parseToString(inputStream);

            if (text == null || text.isBlank()) {
                throw new IllegalStateException("No text extracted from PDF");
            }

            text = text.replaceAll("\\s+", " ").trim();

            List<Document> docs = chunkText(text, CHUNK_SIZE, CHUNK_OVERLAP);
            System.out.println("Chunks created: " + docs.size());

            vectorStore.add(docs);

            System.out.println("Vector store loaded successfully");
        } catch (Exception e) {
            throw new IllegalStateException("Failed to load PDF into vector store", e);
        }
    }

    private List<Document> chunkText(String text, int chunkSize, int overlap) {
        List<Document> chunks = new ArrayList<>();
        int start = 0;

        while (start < text.length()) {
            int end = Math.min(start + chunkSize, text.length());
            String chunk = text.substring(start, end).trim();

            if (!chunk.isEmpty()) {
                chunks.add(new Document(chunk));
            }

            if (end == text.length()) {
                break;
            }

            start = Math.max(end - overlap, start + 1);
        }

        return chunks;
    }
}
